### ISSUE TITLE
Create prefab for lab environment

### ISSUE THREAD

**Issue by tomdewildt** [chemistry-lab/chemistry-lab-experiments#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The lab should have the atom visualization, atom validation, building and a way to combine multiple atoms into a molecule.

It should also have a very nice look:)

**Describe alternatives you've considered**

**Additional context**

**Comment by SvanSomeren** [comment]
Discuss placement of some stuff with the team.
