### ISSUE TITLE
Grabbable objects are colliding with the player

### ISSUE THREAD

**Issue by tomdewildt** [chemistry-lab/chemistry-lab-experiments#39]
**Describe the bug**
Grabbable objects can collide with the player. As a result of this the player can glitch through walls, ceilings and floors.

**To Reproduce**
1. Load interaction experiment
2. Grab an object
3. Push the controller against your belly
4. See problem

**Expected behavior**
Grabbable objects do not collide with the player.

**Screenshots**

**Environment**
(please complete the following information):
 - OS: `Windows`
 - Version: `Latest`

**Additional context**
Possible solutions to the problem described in [this](https://forum.unity.com/threads/how-to-prevent-grabbed-objects-from-physically-interacting-with-player.556186/) thread.

**Comment by Bstijn** [comment]
resolved with #48
